#---------------------------------------------
# %file% - ????
# 
#   Copyright (C) %cyear%  
#     by %name% <%mail%> 
#     Date : %cdate%
#---------------------------------------------

all:

install:all

uninstall:

clean: